import { type IOptions } from "sanitize-html";

export const sanitizeOptions: IOptions = {
  allowedTags: [
    "a",
    "blockquote",
    "br",
    "col",
    "colgroup",
    "figcaption",
    "figure",
    "h2",
    "h3",
    "h4",
    "h5",
    "hr",
    "i",
    "img",
    "input",
    "label",
    "li",
    "ol",
    "p",
    "s",
    "span",
    "strong",
    "sub",
    "sup",
    "table",
    "tbody",
    "td",
    "th",
    "thead",
    "tr",
    "u",
    "ul",
  ],
  allowedAttributes: {
    a: ["href", "rel", "target"],
    col: ["style"],
    figure: ["class", "style"],
    h2: ["style"],
    h3: ["style"],
    h4: ["style"],
    h5: ["style"],
    img: ["alt", "class", "height", "src", "style", "width"],
    input: [
      { name: "checked", values: [] },
      { name: "disabled", values: [] },
      { name: "type", values: ["checkbox"] },
    ],
    label: ["class"],
    ol: ["style"],
    p: ["style"],
    span: ["class", "style"],
    table: ["class", "style"],
    td: ["colspan", "rowspan", "style"],
    th: ["colspan", "rowspan", "style"],
    ul: ["class"],
  },
  allowedSchemes: ["http", "https", "mailto", "tel"],
  nonBooleanAttributes: ["class", "href", "id", "rel", "style", "target"],
  selfClosing: ["br", "hr", "img", "input"],
};
