export default {
  clearMocks: true,
  displayName: "AppServer",
  errorOnDeprecated: true,
  moduleFileExtensions: ["ts", "js"],
  moduleNameMapper: {
    "^@server$": "<rootDir>/src",
    "^@controllers/(.*)$": "<rootDir>/src/controllers/$1",
    "^@events/(.*)$": "<rootDir>/src/events/$1",
    "^@lib/(.*)$": "<rootDir>/src/lib/$1",
    "^@services/(.*)$": "<rootDir>/src/services/$1",
    "^@middleware/(.*)$": "<rootDir>/src/middleware/$1",
    "^@types$": "<rootDir>/src/types",
    "^@resolverTypes$": "<rootDir>/src/types/resolverTypes",
    "^@validators/(.*)$": "<rootDir>/src/validators/$1",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@typeResolvers/(.*)$": "<rootDir>/src/resolvers/typeResolvers/$1",
  },
  setupFiles: ["dotenv/config"],
  testEnvironment: "node",
  verbose: true,
};
