export const BaseResponse = [
  "AuthenticationError",
  "NotAllowedError",
  "RegistrationError",
  "ServerError",
  "UnauthorizedAuthorError",
  "UnknownError",
  "UserSessionError",
  "Response",
  "DuplicatePostTitleError",
  "EmptyBinWarning",
  "NotAllowedPostActionError",
  "PostsWarning",
  "DuplicatePostTagError",
  "PostTagsWarning",
];
