import mailService from ".";
import mailTemplate from "./mailTemplate";
import { MailError } from "@lib/Errors";
import { urls } from "@lib/ClientUrls";

const createUserMail = async (email: string, password: string) => {
  const body = `
    <p>
      You have been added as a new user to Fawller Speaks Admin.
    </p>
    <p  style="margin:15px 0">
      Please copy the autogenerated password below and head over to the <a href="${urls.login}" target="_blank" rel="nofollow noopener noreferrer" style="color:#6a6a6a;font-weight:bold">admin dashboard</a> to log in.
    </p>
    <p>
      You will be mandated upon initial login to change from the autogenerated password to a preferred password of your choice when you register your account.
    </p>
    <p style="margin-top:25px">
      <span>Auto generated password:</span>
      <span style="background-color:#7dd1f3;border-radius:5px;padding:20px;display:inline-block;color:#404040;font-weight:bold;letter-spacing:0.5px">${password}</span>
    </p>
  `;

  const text = `
    Fawller Speaks

    ---

    You have been added as a new user to Fawller Speaks Admin.

    Please copy the autogenerated password below and head over to the admin dashboard ${urls.login} to log in.

    You will be mandated upon initial login to change from the autogenerated password to a preferred password of your choice when you register your account.

    Auto generated password: ${password}
  `;

  const subject = "Fawller Speaks Admin New User";
  const html = mailTemplate(body);

  try {
    await mailService.send({ to: email, subject, html, text });
  } catch (e) {
    const msg = `A confirmation mail could not be sent for the creation of a new user with email ${email}`;

    throw new MailError(
      `${msg}${e instanceof Error ? `. Error: ${e.message}` : ""}`,
    );
  }
};

export default createUserMail;
