import { sendMail } from "@lib/mailService";
import { MailError } from "@utils/Errors";
import { urls } from "@utils/ClientUrls";

const createUserMail = async (email: string, password: string) => {
  const html = `
    <div
      style="
        font-family: Verdana, sans-serif;
        color: #404040;
        text-align: center;
        background-color: #fff;
        max-width: 900px;
        margin: 0 auto;
        padding: 10px;
      "
    >
      <h1 style="color: #7dd1f3">Fawller Speaks</h1>
      <div>
        <p>
          You received this mail because you have been added as a new user to Fawller Speaks Admin.
        </p>
        <p>
          Please copy the password below and head over to our <a href=${urls.login} style="color: #6a6a6a; font-weight: bold">admin console</a> to log in.
        </p>
        <p>
          The password below is autogenerated and you will be mandated to change it upon your first log in attempt.
        </p>
      </div>
      <div style="margin-top: 25px">
        <span>Password:</span>
        <span
          style="
            background-color: #7dd1f3;
            border-radius: 5px;
            padding: 20px;
            display: inline-block;
            color: #404040;
            font-weight: bold;
            letter-spacing: 0.5px;
          "
        >
          ${password}
        </span>
      </div>
    </div>
`;

  const text = `
    Fawller Speaks
    --------------

    You received this mail because you have been added as a new user to Fawller Speaks Admin.

    Please copy the password below and head over to our admin console at ${urls.login} to log in.

    The password below is autogenerated and you will be mandated to change it upon your first log in attempt.

    Password: ${password}
  `;

  const subject = "Fawller Speaks Admin New User";

  try {
    await sendMail({ to: email, subject, text, html });
  } catch {
    throw new MailError(
      "Unable to send confirmation mail. Please try again later"
    );
  }
};

export default createUserMail;
